### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by rkdan** [acceleratescience/conceptual-cartography#1]
## Current state
Given a config file
```yaml
model:
  model_name: 'Alibaba-NLP/gte-base-en-v1.5'
data:
  sentences_path: 'data/testing_data/bank_test.txt'
  output_path: 'output'
experiment:
  model_batch_size: 32
  context_window: None
  target_word: 'bank'
```

software produces something like
```
.
└── sentence-transformers_all-MiniLM-L6-v2
    ├── window_20
    │   └── theory
    │       ├── contexts.txt
    │       ├── final_embeddings.pt
    │       ├── hidden_embeddings.pt
    │       └── indices.txt
    └── window_None
        ├── duty
        │   ├── contexts.txt
        │   ├── final_embeddings.pt
        │   ├── hidden_embeddings.pt
        │   └── indices.txt
        └── theory
            ├── contexts.txt
            ├── final_embeddings.pt
            ├── hidden_embeddings.pt
            └── indices.txt
```
Ordering might be important here -- it is intended for a single corpus, but people might want to explore multiple models for a single word and context size, or multiple words for a single model, etc. For now, the structure is `model/context_size/word`.

We want to retain the ability for users to just be able to get the hidden states and do whatever with them. But we also want to generate:

- metrics
- conceptual landscapes

Code for metrics is written.

## Next work
Extend to save metrics.
